/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: sMD1pVj9GCeDqp5pGdZGXp
// Component: 9B-lV6Ip9v_z

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: sMD1pVj9GCeDqp5pGdZGXp/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: sMD1pVj9GCeDqp5pGdZGXp/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: sMD1pVj9GCeDqp5pGdZGXp/projectcss
import sty from "./PlasmicGuide1.module.css"; // plasmic-import: 9B-lV6Ip9v_z/css

createPlasmicElementProxy;

export type PlasmicGuide1__VariantMembers = {};
export type PlasmicGuide1__VariantsArgs = {};
type VariantPropType = keyof PlasmicGuide1__VariantsArgs;
export const PlasmicGuide1__VariantProps = new Array<VariantPropType>();

export type PlasmicGuide1__ArgsType = {
  children?: React.ReactNode;
  slot?: React.ReactNode;
  slot2?: React.ReactNode;
  slot3?: React.ReactNode;
  slot4?: React.ReactNode;
};
type ArgPropType = keyof PlasmicGuide1__ArgsType;
export const PlasmicGuide1__ArgProps = new Array<ArgPropType>(
  "children",
  "slot",
  "slot2",
  "slot3",
  "slot4"
);

export type PlasmicGuide1__OverridesType = {
  root?: Flex__<"div">;
  heroHeadline4?: Flex__<"div">;
  paragraph26?: Flex__<"div">;
  paragraph27?: Flex__<"div">;
};

export interface DefaultGuide1Props {
  children?: React.ReactNode;
  slot?: React.ReactNode;
  slot2?: React.ReactNode;
  slot3?: React.ReactNode;
  slot4?: React.ReactNode;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicGuide1__RenderFunc(props: {
  variants: PlasmicGuide1__VariantsArgs;
  args: PlasmicGuide1__ArgsType;
  overrides: PlasmicGuide1__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox__pulHm)}>
        {renderPlasmicSlot({
          defaultContents: (
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.link__t6BgW
              )}
              component={Link}
              platform={"nextjs"}
            >
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__rDz6L)}
                displayHeight={"440px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"440px"}
                loading={"eager"}
              />
            </PlasmicLink__>
          ),
          value: args.children
        })}
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__nCu6O)}>
        <div className={classNames(projectcss.all, sty.freeBox__a4NeE)}>
          <div className={classNames(projectcss.all, sty.freeBox__q2E2B)}>
            <div className={classNames(projectcss.all, sty.freeBox__wyMmT)}>
              {renderPlasmicSlot({
                defaultContents: "1",
                value: args.slot,
                className: classNames(sty.slotTargetSlot)
              })}
            </div>
          </div>
          <div
            data-plasmic-name={"heroHeadline4"}
            data-plasmic-override={overrides.heroHeadline4}
            className={classNames(projectcss.all, sty.heroHeadline4)}
          >
            {renderPlasmicSlot({
              defaultContents: "Microplastics in Everyday Items",
              value: args.slot2,
              className: classNames(sty.slotTargetSlot2)
            })}
          </div>
        </div>
        <div
          data-plasmic-name={"paragraph26"}
          data-plasmic-override={overrides.paragraph26}
          className={classNames(projectcss.all, sty.paragraph26)}
        >
          {renderPlasmicSlot({
            defaultContents:
              "You wash your sheets. \n\nYou vacuum your mattress. \n\nYou even splurged on a better pillow.\n\nBut there\u2019s one invisible threat in your bed that no amount of cleaning will remove \u2014 and most people sleep in it every single night.",
            value: args.slot3,
            className: classNames(sty.slotTargetSlot3)
          })}
        </div>
        <div
          data-plasmic-name={"paragraph27"}
          data-plasmic-override={overrides.paragraph27}
          className={classNames(projectcss.all, sty.paragraph27)}
        >
          {renderPlasmicSlot({
            defaultContents: "Shop Product \u2192",
            value: args.slot4,
            className: classNames(sty.slotTargetSlot4)
          })}
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "heroHeadline4", "paragraph26", "paragraph27"],
  heroHeadline4: ["heroHeadline4"],
  paragraph26: ["paragraph26"],
  paragraph27: ["paragraph27"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  heroHeadline4: "div";
  paragraph26: "div";
  paragraph27: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicGuide1__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicGuide1__VariantsArgs;
    args?: PlasmicGuide1__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicGuide1__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicGuide1__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicGuide1__ArgProps,
          internalVariantPropNames: PlasmicGuide1__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicGuide1__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicGuide1";
  } else {
    func.displayName = `PlasmicGuide1.${nodeName}`;
  }
  return func;
}

export const PlasmicGuide1 = Object.assign(
  // Top-level PlasmicGuide1 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    heroHeadline4: makeNodeComponent("heroHeadline4"),
    paragraph26: makeNodeComponent("paragraph26"),
    paragraph27: makeNodeComponent("paragraph27"),

    // Metadata about props expected for PlasmicGuide1
    internalVariantProps: PlasmicGuide1__VariantProps,
    internalArgProps: PlasmicGuide1__ArgProps
  }
);

export default PlasmicGuide1;
/* prettier-ignore-end */
