/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: sMD1pVj9GCeDqp5pGdZGXp

import { createUseStyleTokens } from "@plasmicapp/react-web";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: sMD1pVj9GCeDqp5pGdZGXp/projectModule

import projectcss from "./plasmic.module.css"; // plasmic-import: sMD1pVj9GCeDqp5pGdZGXp/projectcss

const data = {
  base: `${projectcss.plasmic_tokens}`,
  varianted: []
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);
