/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: sMD1pVj9GCeDqp5pGdZGXp
// Component: EAv1RjrZKbU_

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: sMD1pVj9GCeDqp5pGdZGXp/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: sMD1pVj9GCeDqp5pGdZGXp/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: sMD1pVj9GCeDqp5pGdZGXp/projectcss
import sty from "./PlasmicValueStack5.module.css"; // plasmic-import: EAv1RjrZKbU_/css

createPlasmicElementProxy;

export type PlasmicValueStack5__VariantMembers = {};
export type PlasmicValueStack5__VariantsArgs = {};
type VariantPropType = keyof PlasmicValueStack5__VariantsArgs;
export const PlasmicValueStack5__VariantProps = new Array<VariantPropType>();

export type PlasmicValueStack5__ArgsType = {
  children?: React.ReactNode;
  slot?: React.ReactNode;
  slot2?: React.ReactNode;
  slot3?: React.ReactNode;
  slot4?: React.ReactNode;
  slot5?: React.ReactNode;
  slot6?: React.ReactNode;
};
type ArgPropType = keyof PlasmicValueStack5__ArgsType;
export const PlasmicValueStack5__ArgProps = new Array<ArgPropType>(
  "children",
  "slot",
  "slot2",
  "slot3",
  "slot4",
  "slot5",
  "slot6"
);

export type PlasmicValueStack5__OverridesType = {
  root?: Flex__<"div">;
  link?: Flex__<"a"> & Partial<LinkProps>;
};

export interface DefaultValueStack5Props {
  children?: React.ReactNode;
  slot?: React.ReactNode;
  slot2?: React.ReactNode;
  slot3?: React.ReactNode;
  slot4?: React.ReactNode;
  slot5?: React.ReactNode;
  slot6?: React.ReactNode;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicValueStack5__RenderFunc(props: {
  variants: PlasmicValueStack5__VariantsArgs;
  args: PlasmicValueStack5__ArgsType;
  overrides: PlasmicValueStack5__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox__ju5Gm)}>
        <div className={classNames(projectcss.all, sty.freeBox___9Zohx)}>
          <div className={classNames(projectcss.all, sty.freeBox__w2BMn)}>
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img___0U4Jt)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
            />
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__m92D)}>
            <div className={classNames(projectcss.all, sty.freeBox__reMss)}>
              {renderPlasmicSlot({
                defaultContents: (
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__uqRz
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#636363" }}
                      >
                        {"Advanced TikTok & Facebook Ads Training:"}
                      </span>
                    </React.Fragment>
                  </div>
                ),
                value: args.children,
                className: classNames(sty.slotTargetChildren)
              })}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__uLO
              )}
            >
              {"Enter some text"}
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__dueN)}>
            <div className={classNames(projectcss.all, sty.freeBox__mdDix)}>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__a16Fx)}
                displayHeight={"24px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"24px"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/grund/images/downloadSvg2.svg",
                  fullWidth: 150,
                  fullHeight: 150,
                  aspectRatio: 1
                }}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__wdEo9
                )}
              >
                {"Instant Access"}
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox___4DLd)}>
            <div className={classNames(projectcss.all, sty.freeBox__dztDa)}>
              <div className={classNames(projectcss.all, sty.freeBox__tJY)}>
                {renderPlasmicSlot({
                  defaultContents: "Price: $9,997+",
                  value: args.slot,
                  className: classNames(sty.slotTargetSlot)
                })}
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__exiWj)}>
            <PlasmicLink__
              data-plasmic-name={"link"}
              data-plasmic-override={overrides.link}
              className={classNames(projectcss.all, projectcss.a, sty.link)}
              component={Link}
              platform={"nextjs"}
            >
              {renderPlasmicSlot({
                defaultContents: (
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xaYx7
                    )}
                  >
                    {"\ud83d\udc49  FREE  \ud83d\udc48"}
                  </div>
                ),
                value: args.slot2
              })}
            </PlasmicLink__>
          </div>
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__owQng)}>
          <div className={classNames(projectcss.all, sty.freeBox__vEMsR)}>
            <div className={classNames(projectcss.all, sty.freeBox__gZ8YO)}>
              {renderPlasmicSlot({
                defaultContents:
                  "Learn How to Generate Profitable Traffic for Any Store With Zendrop Academy.",
                value: args.slot3
              })}
            </div>
          </div>
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__uAAb)}>
          <div className={classNames(projectcss.all, sty.freeBox__wGV0)}>
            <div className={classNames(projectcss.all, sty.freeBox__narhl)}>
              <div className={classNames(projectcss.all, sty.freeBox__zeCkZ)}>
                <div className={classNames(projectcss.all, sty.freeBox__gEaB7)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__etXrr)}
                    displayHeight={"80px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"120px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/grund/images/timBurdTalkPng.png",
                      fullWidth: 240,
                      fullHeight: 160,
                      aspectRatio: undefined
                    }}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__b4Xi)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__amFjs
                    )}
                  >
                    {"Tim Burd Mastermind Presentation"}
                  </div>
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox___6TxBu)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__wo8JD)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__dv58K)}
                    >
                      {renderPlasmicSlot({
                        defaultContents: "Price: $2,997",
                        value: args.slot4,
                        className: classNames(sty.slotTargetSlot4)
                      })}
                    </div>
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__jZyXj)}>
                <div
                  className={classNames(projectcss.all, sty.freeBox___5TYsw)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__w0TUv)}
                    displayHeight={"80px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"120px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/grund/images/justinWoolPng.png",
                      fullWidth: 240,
                      fullHeight: 160,
                      aspectRatio: undefined
                    }}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__dmYbo)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___8JlzK
                    )}
                  >
                    {"Justin Wool Mastermind Presentation"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__wHevO)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___1X3D5)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__qiFrS)}
                    >
                      {renderPlasmicSlot({
                        defaultContents: "Price: $2,997",
                        value: args.slot5,
                        className: classNames(sty.slotTargetSlot5)
                      })}
                    </div>
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__n4Tpf)}>
                <div className={classNames(projectcss.all, sty.freeBox__zs8Ef)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__nGSjZ)}
                    displayHeight={"80px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"120px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/grund/images/academy600450Px800450Px6Png.png",
                      fullWidth: 798,
                      fullHeight: 449,
                      aspectRatio: undefined
                    }}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__dT5Az)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kXUi
                    )}
                  >
                    {"Plus 50+ High-Value Modules"}
                  </div>
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox___9VfeQ)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__yb6Fx)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__adaj)}
                    >
                      {renderPlasmicSlot({
                        defaultContents: "Price: $2,997",
                        value: args.slot6,
                        className: classNames(sty.slotTargetSlot6)
                      })}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "link"],
  link: ["link"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  link: "a";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicValueStack5__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicValueStack5__VariantsArgs;
    args?: PlasmicValueStack5__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicValueStack5__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicValueStack5__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicValueStack5__ArgProps,
          internalVariantPropNames: PlasmicValueStack5__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicValueStack5__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicValueStack5";
  } else {
    func.displayName = `PlasmicValueStack5.${nodeName}`;
  }
  return func;
}

export const PlasmicValueStack5 = Object.assign(
  // Top-level PlasmicValueStack5 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    link: makeNodeComponent("link"),

    // Metadata about props expected for PlasmicValueStack5
    internalVariantProps: PlasmicValueStack5__VariantProps,
    internalArgProps: PlasmicValueStack5__ArgProps
  }
);

export default PlasmicValueStack5;
/* prettier-ignore-end */
