/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: sMD1pVj9GCeDqp5pGdZGXp
// Component: kMibmO7fOwuu

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: sMD1pVj9GCeDqp5pGdZGXp/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: sMD1pVj9GCeDqp5pGdZGXp/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: sMD1pVj9GCeDqp5pGdZGXp/projectcss
import sty from "./PlasmicValueStack4.module.css"; // plasmic-import: kMibmO7fOwuu/css

createPlasmicElementProxy;

export type PlasmicValueStack4__VariantMembers = {};
export type PlasmicValueStack4__VariantsArgs = {};
type VariantPropType = keyof PlasmicValueStack4__VariantsArgs;
export const PlasmicValueStack4__VariantProps = new Array<VariantPropType>();

export type PlasmicValueStack4__ArgsType = {
  children?: React.ReactNode;
  slot?: React.ReactNode;
  slot2?: React.ReactNode;
  slot3?: React.ReactNode;
};
type ArgPropType = keyof PlasmicValueStack4__ArgsType;
export const PlasmicValueStack4__ArgProps = new Array<ArgPropType>(
  "children",
  "slot",
  "slot2",
  "slot3"
);

export type PlasmicValueStack4__OverridesType = {
  root?: Flex__<"div">;
  link?: Flex__<"a"> & Partial<LinkProps>;
};

export interface DefaultValueStack4Props {
  children?: React.ReactNode;
  slot?: React.ReactNode;
  slot2?: React.ReactNode;
  slot3?: React.ReactNode;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicValueStack4__RenderFunc(props: {
  variants: PlasmicValueStack4__VariantsArgs;
  args: PlasmicValueStack4__ArgsType;
  overrides: PlasmicValueStack4__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox__ts80D)}>
        <div className={classNames(projectcss.all, sty.freeBox__czbZt)}>
          <div className={classNames(projectcss.all, sty.freeBox__afkuV)}>
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__d1Og9)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
            />
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__caM77)}>
            <div className={classNames(projectcss.all, sty.freeBox__ebbdo)}>
              {renderPlasmicSlot({
                defaultContents: (
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__sKzJu
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#636363" }}
                      >
                        {"30-Day Zendrop PLUS App Free Trial:"}
                      </span>
                    </React.Fragment>
                  </div>
                ),
                value: args.children,
                className: classNames(sty.slotTargetChildren)
              })}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__mhLIz
              )}
            >
              {"Enter some text"}
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__ouqt)}>
            <div className={classNames(projectcss.all, sty.freeBox__ozwnV)}>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__xbyp)}
                displayHeight={"24px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"24px"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/grund/images/downloadSvg2.svg",
                  fullWidth: 150,
                  fullHeight: 150,
                  aspectRatio: 1
                }}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__y9LJk
                )}
              >
                {"Instant Access"}
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__wiQ7)}>
            <div className={classNames(projectcss.all, sty.freeBox__iUVmF)}>
              <div className={classNames(projectcss.all, sty.freeBox__a6Fl0)}>
                {renderPlasmicSlot({
                  defaultContents: "Price: $2,997",
                  value: args.slot,
                  className: classNames(sty.slotTargetSlot)
                })}
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox___8JyS6)}>
            <PlasmicLink__
              data-plasmic-name={"link"}
              data-plasmic-override={overrides.link}
              className={classNames(projectcss.all, projectcss.a, sty.link)}
              component={Link}
              href={"https://zendrop.com/checkout-trial-fb/"}
              platform={"nextjs"}
            >
              {renderPlasmicSlot({
                defaultContents: (
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ipoDt
                    )}
                  >
                    {"\ud83d\udc49  FREE  \ud83d\udc48"}
                  </div>
                ),
                value: args.slot2
              })}
            </PlasmicLink__>
          </div>
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__zw2Gk)}>
          <div className={classNames(projectcss.all, sty.freeBox__oFb0M)}>
            <div className={classNames(projectcss.all, sty.freeBox__q2XGz)}>
              {renderPlasmicSlot({
                defaultContents:
                  "Network and learn from some of the top dropshippers on the planet. ",
                value: args.slot3
              })}
            </div>
          </div>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "link"],
  link: ["link"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  link: "a";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicValueStack4__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicValueStack4__VariantsArgs;
    args?: PlasmicValueStack4__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicValueStack4__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicValueStack4__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicValueStack4__ArgProps,
          internalVariantPropNames: PlasmicValueStack4__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicValueStack4__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicValueStack4";
  } else {
    func.displayName = `PlasmicValueStack4.${nodeName}`;
  }
  return func;
}

export const PlasmicValueStack4 = Object.assign(
  // Top-level PlasmicValueStack4 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    link: makeNodeComponent("link"),

    // Metadata about props expected for PlasmicValueStack4
    internalVariantProps: PlasmicValueStack4__VariantProps,
    internalArgProps: PlasmicValueStack4__ArgProps
  }
);

export default PlasmicValueStack4;
/* prettier-ignore-end */
