/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: sMD1pVj9GCeDqp5pGdZGXp
// Component: FOhUZUepx6np

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: sMD1pVj9GCeDqp5pGdZGXp/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: sMD1pVj9GCeDqp5pGdZGXp/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: sMD1pVj9GCeDqp5pGdZGXp/projectcss
import sty from "./PlasmicValueStack2.module.css"; // plasmic-import: FOhUZUepx6np/css

createPlasmicElementProxy;

export type PlasmicValueStack2__VariantMembers = {};
export type PlasmicValueStack2__VariantsArgs = {};
type VariantPropType = keyof PlasmicValueStack2__VariantsArgs;
export const PlasmicValueStack2__VariantProps = new Array<VariantPropType>();

export type PlasmicValueStack2__ArgsType = {
  children?: React.ReactNode;
  slot?: React.ReactNode;
  slot2?: React.ReactNode;
  slot3?: React.ReactNode;
  slot4?: React.ReactNode;
  slot5?: React.ReactNode;
  slot6?: React.ReactNode;
  children2?: React.ReactNode;
  slot7?: React.ReactNode;
  slot8?: React.ReactNode;
  slot9?: React.ReactNode;
  slot10?: React.ReactNode;
  slot11?: React.ReactNode;
  slot12?: React.ReactNode;
};
type ArgPropType = keyof PlasmicValueStack2__ArgsType;
export const PlasmicValueStack2__ArgProps = new Array<ArgPropType>(
  "children",
  "slot",
  "slot2",
  "slot3",
  "slot4",
  "slot5",
  "slot6",
  "children2",
  "slot7",
  "slot8",
  "slot9",
  "slot10",
  "slot11",
  "slot12"
);

export type PlasmicValueStack2__OverridesType = {
  root?: Flex__<"div">;
  desktop?: Flex__<"div">;
  mobile?: Flex__<"div">;
};

export interface DefaultValueStack2Props {
  children?: React.ReactNode;
  slot?: React.ReactNode;
  slot2?: React.ReactNode;
  slot3?: React.ReactNode;
  slot4?: React.ReactNode;
  slot5?: React.ReactNode;
  slot6?: React.ReactNode;
  children2?: React.ReactNode;
  slot7?: React.ReactNode;
  slot8?: React.ReactNode;
  slot9?: React.ReactNode;
  slot10?: React.ReactNode;
  slot11?: React.ReactNode;
  slot12?: React.ReactNode;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicValueStack2__RenderFunc(props: {
  variants: PlasmicValueStack2__VariantsArgs;
  args: PlasmicValueStack2__ArgsType;
  overrides: PlasmicValueStack2__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"desktop"}
        data-plasmic-override={overrides.desktop}
        className={classNames(projectcss.all, sty.desktop)}
      >
        <div className={classNames(projectcss.all, sty.freeBox__toca1)}>
          <div className={classNames(projectcss.all, sty.freeBox___1Ae7C)}>
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img___4Y39L)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
            />
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__keNTr)}>
            <div className={classNames(projectcss.all, sty.freeBox__v6TQk)}>
              {renderPlasmicSlot({
                defaultContents: (
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__yjqTx
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#636363" }}
                      >
                        {"Advanced TikTok & Facebook Ads Training:"}
                      </span>
                    </React.Fragment>
                  </div>
                ),
                value: args.children,
                className: classNames(sty.slotTargetChildren)
              })}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__yhICo
              )}
            >
              {"Enter some text"}
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__zVQeq)}>
            <div className={classNames(projectcss.all, sty.freeBox__rvFdG)}>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__bnY)}
                displayHeight={"24px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"24px"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/grund/images/downloadSvg2.svg",
                  fullWidth: 150,
                  fullHeight: 150,
                  aspectRatio: 1
                }}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__sm7R
                )}
              >
                {"Instant Access"}
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__c0Inb)}>
            <div className={classNames(projectcss.all, sty.freeBox__kGOea)}>
              <div className={classNames(projectcss.all, sty.freeBox__pMJp7)}>
                {renderPlasmicSlot({
                  defaultContents: "Price: $9,997+",
                  value: args.slot,
                  className: classNames(sty.slotTargetSlot)
                })}
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__yWgew)}>
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.link___0Y2Gl
              )}
              component={Link}
              platform={"nextjs"}
            >
              {renderPlasmicSlot({
                defaultContents: (
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___5WD5H
                    )}
                  >
                    {"\ud83d\udc49  FREE  \ud83d\udc48"}
                  </div>
                ),
                value: args.slot2
              })}
            </PlasmicLink__>
          </div>
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__ebvRa)}>
          <div className={classNames(projectcss.all, sty.freeBox__v3Zjz)}>
            <div className={classNames(projectcss.all, sty.freeBox__ot563)}>
              {renderPlasmicSlot({
                defaultContents:
                  "Learn How to Generate Profitable Traffic for Any Store With Zendrop Academy.",
                value: args.slot3
              })}
            </div>
          </div>
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__qHTbM)}>
          <div className={classNames(projectcss.all, sty.freeBox__oW8Aq)}>
            <div className={classNames(projectcss.all, sty.freeBox__nGwws)}>
              <div className={classNames(projectcss.all, sty.freeBox___1Lks7)}>
                <div
                  className={classNames(projectcss.all, sty.freeBox___2Dgv5)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__kihWr)}
                    displayHeight={"80px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"120px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/grund/images/timBurdTalkPng.png",
                      fullWidth: 240,
                      fullHeight: 160,
                      aspectRatio: undefined
                    }}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__h1Arz)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__uxF8V
                    )}
                  >
                    {"Tim Burd Mastermind Presentation"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__cP78N)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__m3V2P)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__sOycn)}
                    >
                      {renderPlasmicSlot({
                        defaultContents: "Price: $2,997",
                        value: args.slot4,
                        className: classNames(sty.slotTargetSlot4)
                      })}
                    </div>
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox___49AgK)}>
                <div className={classNames(projectcss.all, sty.freeBox__yU79P)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__ubG7T)}
                    displayHeight={"80px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"120px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/grund/images/justinWoolPng.png",
                      fullWidth: 240,
                      fullHeight: 160,
                      aspectRatio: undefined
                    }}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__jIlYs)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ih7Oi
                    )}
                  >
                    {"Justin Wool Mastermind Presentation"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__icw3O)}>
                  <div className={classNames(projectcss.all, sty.freeBox__rCz)}>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__dc7TX)}
                    >
                      {renderPlasmicSlot({
                        defaultContents: "Price: $2,997",
                        value: args.slot5,
                        className: classNames(sty.slotTargetSlot5)
                      })}
                    </div>
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__riqhw)}>
                <div className={classNames(projectcss.all, sty.freeBox__ndQws)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__kYrS7)}
                    displayHeight={"80px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"120px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/grund/images/academy600450Px800450Px6Png.png",
                      fullWidth: 798,
                      fullHeight: 449,
                      aspectRatio: undefined
                    }}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__wIc3R)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__nREvG
                    )}
                  >
                    {"Plus 50+ High-Value Modules"}
                  </div>
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox___7T1YW)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox___9PeLy)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__wzIBi)}
                    >
                      {renderPlasmicSlot({
                        defaultContents: "Price: $2,997",
                        value: args.slot6,
                        className: classNames(sty.slotTargetSlot6)
                      })}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      {(hasVariant(globalVariants, "screen", "mobileOnly") ? true : false) ? (
        <div
          data-plasmic-name={"mobile"}
          data-plasmic-override={overrides.mobile}
          className={classNames(projectcss.all, sty.mobile)}
        >
          <div className={classNames(projectcss.all, sty.freeBox__by5J)}>
            <div className={classNames(projectcss.all, sty.freeBox__oNufA)}>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__h03Nw)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
              />
            </div>
            <div className={classNames(projectcss.all, sty.freeBox___1Wl4L)}>
              <div className={classNames(projectcss.all, sty.freeBox__dmFqF)}>
                {renderPlasmicSlot({
                  defaultContents: (
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__vRllp
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ color: "#636363" }}
                        >
                          {"Advanced TikTok & Facebook Ads Training:"}
                        </span>
                      </React.Fragment>
                    </div>
                  ),
                  value: args.children2,
                  className: classNames(sty.slotTargetChildren2)
                })}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__lrG6
                )}
              >
                {"Enter some text"}
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__aVzE)}>
              <PlasmicLink__
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.link__dUwcf
                )}
                component={Link}
                platform={"nextjs"}
              >
                {renderPlasmicSlot({
                  defaultContents: (
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__mwnHk
                      )}
                    >
                      {"\ud83d\udc49  FREE  \ud83d\udc48"}
                    </div>
                  ),
                  value: args.slot8
                })}
              </PlasmicLink__>
              <div className={classNames(projectcss.all, sty.freeBox__roBjm)}>
                <div className={classNames(projectcss.all, sty.freeBox__uzOJi)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__jWqUo)}
                  >
                    {renderPlasmicSlot({
                      defaultContents: "Price: $9,997+",
                      value: args.slot7,
                      className: classNames(sty.slotTargetSlot7)
                    })}
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__srMim)}>
            <div className={classNames(projectcss.all, sty.freeBox__kQxmK)}>
              <div className={classNames(projectcss.all, sty.freeBox__wpkG)}>
                {renderPlasmicSlot({
                  defaultContents:
                    "Learn How to Generate Profitable Traffic for Any Store With Zendrop Academy.",
                  value: args.slot9
                })}
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__iz3Em)}>
            <div className={classNames(projectcss.all, sty.freeBox__gtSe)}>
              <div className={classNames(projectcss.all, sty.freeBox__adNj0)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__kckr1)}
                  displayHeight={"24px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"24px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/grund/images/downloadSvg2.svg",
                    fullWidth: 150,
                    fullHeight: 150,
                    aspectRatio: 1
                  }}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__tFaV0
                  )}
                >
                  {"Instant Access"}
                </div>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__g4085)}>
            <div className={classNames(projectcss.all, sty.freeBox__nRc9W)}>
              <div className={classNames(projectcss.all, sty.freeBox__jsEDi)}>
                <div
                  className={classNames(projectcss.all, sty.freeBox___2VVfp)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox___5Cp15)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__ieTce)}
                      displayHeight={"80px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"120px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/grund/images/timBurdTalkPng.png",
                        fullWidth: 240,
                        fullHeight: 160,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__wPxi6)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__krcX
                      )}
                    >
                      {"Tim Burd Mastermind Presentation"}
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__xoBq0)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__sOfD
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__jUprq
                          )}
                        >
                          {renderPlasmicSlot({
                            defaultContents: "Price: $2,997",
                            value: args.slot10,
                            className: classNames(sty.slotTargetSlot10)
                          })}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__meJcR)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__nYb4A)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__l7Gup)}
                      displayHeight={"80px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"120px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/grund/images/justinWoolPng.png",
                        fullWidth: 240,
                        fullHeight: 160,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__u0ZMb)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__mEvPd
                      )}
                    >
                      {"Justin Wool Mastermind Presentation"}
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__iPAdO)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__ebQg
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___45GqU
                          )}
                        >
                          {renderPlasmicSlot({
                            defaultContents: "Price: $2,997",
                            value: args.slot11,
                            className: classNames(sty.slotTargetSlot11)
                          })}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__ieV7V)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__a4Peb)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__wUZk)}
                      displayHeight={"80px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"120px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/grund/images/academy600450Px800450Px6Png.png",
                        fullWidth: 798,
                        fullHeight: 449,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__kqb4C)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__wcveL
                      )}
                    >
                      {"Plus 50+ High-Value Modules"}
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__xtCaM)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__us0J8
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___4Rq43
                          )}
                        >
                          {renderPlasmicSlot({
                            defaultContents: "Price: $2,997",
                            value: args.slot12,
                            className: classNames(sty.slotTargetSlot12)
                          })}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      ) : null}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "desktop", "mobile"],
  desktop: ["desktop"],
  mobile: ["mobile"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  desktop: "div";
  mobile: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicValueStack2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicValueStack2__VariantsArgs;
    args?: PlasmicValueStack2__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicValueStack2__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicValueStack2__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicValueStack2__ArgProps,
          internalVariantPropNames: PlasmicValueStack2__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicValueStack2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicValueStack2";
  } else {
    func.displayName = `PlasmicValueStack2.${nodeName}`;
  }
  return func;
}

export const PlasmicValueStack2 = Object.assign(
  // Top-level PlasmicValueStack2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    desktop: makeNodeComponent("desktop"),
    mobile: makeNodeComponent("mobile"),

    // Metadata about props expected for PlasmicValueStack2
    internalVariantProps: PlasmicValueStack2__VariantProps,
    internalArgProps: PlasmicValueStack2__ArgProps
  }
);

export default PlasmicValueStack2;
/* prettier-ignore-end */
