/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: sMD1pVj9GCeDqp5pGdZGXp
// Component: gYiLKGz_Ch5E

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Guide1 from "../../Guide1"; // plasmic-import: 9B-lV6Ip9v_z/component
import { Embed } from "@plasmicpkgs/plasmic-basic-components";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: sMD1pVj9GCeDqp5pGdZGXp/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: sMD1pVj9GCeDqp5pGdZGXp/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: sMD1pVj9GCeDqp5pGdZGXp/projectcss
import sty from "./PlasmicGuide.module.css"; // plasmic-import: gYiLKGz_Ch5E/css

import ArrowBigRightSvgIcon from "./icons/PlasmicIcon__ArrowBigRightSvg"; // plasmic-import: 0AnDLiltolyl/icon
import Icons8FacebookSvgIcon from "./icons/PlasmicIcon__Icons8FacebookSvg"; // plasmic-import: OuPKQjhz-sZd/icon
import XLogoSvgIcon from "./icons/PlasmicIcon__XLogoSvg"; // plasmic-import: kXqCWd_Hyuxn/icon
import InstagramSvgIcon from "./icons/PlasmicIcon__InstagramSvg"; // plasmic-import: II1l_zcJtRWT/icon
import Pinterest113SvgIcon from "./icons/PlasmicIcon__Pinterest113Svg"; // plasmic-import: j9zx5QM_cs8f/icon
import TiktokSvgrepoComSvgIcon from "./icons/PlasmicIcon__TiktokSvgrepoComSvg"; // plasmic-import: NiKY4SGqs4XP/icon
import A1Cc5C97117844C0Baed1B594B8441E1SvgIcon from "./icons/PlasmicIcon__A1Cc5C97117844C0Baed1B594B8441E1Svg"; // plasmic-import: YGP4mSCVP01t/icon
import Fe59Bd81Eef94C38B993E0Cdfdef8E8BSvgIcon from "./icons/PlasmicIcon__Fe59Bd81Eef94C38B993E0Cdfdef8E8BSvg"; // plasmic-import: hpv1Ee7gP2Av/icon
import _58E3B3D164Ca451A8D6E3147Cef3AfaaSvgIcon from "./icons/PlasmicIcon___58E3B3D164Ca451A8D6E3147Cef3AfaaSvg"; // plasmic-import: 1jCFXO5sdk0W/icon
import Fd6697B3506648Ff8DacF29E194083CdSvgIcon from "./icons/PlasmicIcon__Fd6697B3506648Ff8DacF29E194083CdSvg"; // plasmic-import: OWtr5KeS8bZX/icon
import Fba2822A173B475C99DbFbc9F6Fd24A9SvgIcon from "./icons/PlasmicIcon__Fba2822A173B475C99DbFbc9F6Fd24A9Svg"; // plasmic-import: Y8_EMk-0tudp/icon
import _7468Cfc1F2Dc4Fc4Bf3CEeb7F2B9066DSvgIcon from "./icons/PlasmicIcon___7468Cfc1F2Dc4Fc4Bf3CEeb7F2B9066DSvg"; // plasmic-import: RwMVaAAy63R6/icon
import _5Af63073Ff5042D9A4E20Eb614673309SvgIcon from "./icons/PlasmicIcon___5Af63073Ff5042D9A4E20Eb614673309Svg"; // plasmic-import: nrNtE3iGv7QG/icon
import _44C55Ab9E76348D3Bbe8Ee81843921EfSvgIcon from "./icons/PlasmicIcon___44C55Ab9E76348D3Bbe8Ee81843921EfSvg"; // plasmic-import: IpXQpkqZ79XH/icon
import F8Cb0Eb974Ed4071B0823B63F191Ba20SvgIcon from "./icons/PlasmicIcon__F8Cb0Eb974Ed4071B0823B63F191Ba20Svg"; // plasmic-import: 11zI2T6wiNHb/icon

createPlasmicElementProxy;

export type PlasmicGuide__VariantMembers = {};
export type PlasmicGuide__VariantsArgs = {};
type VariantPropType = keyof PlasmicGuide__VariantsArgs;
export const PlasmicGuide__VariantProps = new Array<VariantPropType>();

export type PlasmicGuide__ArgsType = {};
type ArgPropType = keyof PlasmicGuide__ArgsType;
export const PlasmicGuide__ArgProps = new Array<ArgPropType>();

export type PlasmicGuide__OverridesType = {
  root?: Flex__<"div">;
  guide1Draft?: Flex__<"div">;
  heroHeadline3?: Flex__<"div">;
  paragraph25?: Flex__<"div">;
  nav?: Flex__<"div">;
  intro?: Flex__<"div">;
  heroHeadline4?: Flex__<"div">;
  heroHeadline5?: Flex__<"div">;
  submitPhonebtn2?: Flex__<"a"> & Partial<LinkProps>;
  footer?: Flex__<"div">;
  embedHtml?: Flex__<typeof Embed>;
  logo3?: Flex__<typeof PlasmicImg__>;
  p?: Flex__<"p">;
  styles?: Flex__<typeof Embed>;
};

export interface DefaultGuideProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicGuide__RenderFunc(props: {
  variants: PlasmicGuide__VariantsArgs;
  args: PlasmicGuide__ArgsType;
  overrides: PlasmicGuide__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary_large_image" />
        <title key="title">{PlasmicGuide.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicGuide.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicGuide.pageMetadata.title}
        />
        <meta
          key="description"
          name="description"
          content={PlasmicGuide.pageMetadata.description}
        />
        <meta
          key="og:description"
          property="og:description"
          content={PlasmicGuide.pageMetadata.description}
        />
        <meta
          key="twitter:description"
          name="twitter:description"
          content={PlasmicGuide.pageMetadata.description}
        />
        <meta
          key="og:image"
          property="og:image"
          content={PlasmicGuide.pageMetadata.ogImageSrc}
        />
        <meta
          key="twitter:image"
          name="twitter:image"
          content={PlasmicGuide.pageMetadata.ogImageSrc}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"guide1Draft"}
            data-plasmic-override={overrides.guide1Draft}
            className={classNames(projectcss.all, sty.guide1Draft)}
          >
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__sdVC)}
              displayHeight={"440px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"440px"}
              loading={"lazy"}
              src={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? {
                      src: "/plasmic/grund/images/image4.jpg",
                      fullWidth: 1920,
                      fullHeight: 1080,
                      aspectRatio: undefined
                    }
                  : undefined
              }
            />

            <div className={classNames(projectcss.all, sty.freeBox___2X48B)}>
              <div className={classNames(projectcss.all, sty.freeBox__eo6Qe)}>
                <div className={classNames(projectcss.all, sty.freeBox__pAEvI)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__wbd74
                    )}
                  >
                    {"1"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"heroHeadline3"}
                  data-plasmic-override={overrides.heroHeadline3}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.heroHeadline3
                  )}
                >
                  {hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "Microplastics in Everyday Items"
                    : "Microplastics in Everyday Items"}
                </div>
              </div>
              <div
                data-plasmic-name={"paragraph25"}
                data-plasmic-override={overrides.paragraph25}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.paragraph25
                )}
              >
                {
                  "You wash your sheets. \n\nYou vacuum your mattress. \n\nYou even splurged on a better pillow.\n\nBut there\u2019s one invisible threat in your bed that no amount of cleaning will remove \u2014 and most people sleep in it every single night."
                }
              </div>
            </div>
          </div>
          <div
            data-plasmic-name={"nav"}
            data-plasmic-override={overrides.nav}
            className={classNames(projectcss.all, sty.nav)}
          >
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.link__h7OxM
              )}
              component={Link}
              href={"https://livegrund.com"}
              platform={"nextjs"}
              target={"_blank"}
            >
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__mi7Pg)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "90px"
                    : "120px"
                }
                loading={"eager"}
                src={{
                  src: "/plasmic/grund/images/grundLogoWhiteVector1Png.png",
                  fullWidth: 582,
                  fullHeight: 200,
                  aspectRatio: undefined
                }}
              />
            </PlasmicLink__>
          </div>
          <div
            data-plasmic-name={"intro"}
            data-plasmic-override={overrides.intro}
            className={classNames(projectcss.all, sty.intro)}
          >
            <div
              data-plasmic-name={"heroHeadline4"}
              data-plasmic-override={overrides.heroHeadline4}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.heroHeadline4
              )}
            >
              {
                "Why Live Grund? Because comfort should never come with compromise."
              }
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__s1C7B
              )}
            >
              {
                "This season, give gifts that feel good in every way for your loved ones, their homes, and the planet. \n\nEvery Live Grund textile is crafted from 100% organic cotton, made without toxins, synthetics, or harsh finishes. \n\nJust clean, timeless comfort designed to support wellbeing.\n\nRooted in European textile craftsmanship and carried forward with modern sustainability led by our family-owned & run business, our collections are designed to outlast fast trends and fast fashion. \n\nThey don\u2019t shed, pill, or disappoint. \n\nThey soften beautifully, elevate any space, and turn daily rituals into moments of calm.\n\nGifts That Truly Matter:\n\n\u2714\ufe0f 100% organic & toxin-free \u2014 safe for skin, safe for home\n\u2714\ufe0f European-inspired luxury \u2014 detailed weaving, elevated textures\n\u2714\ufe0f No synthetics, no microfibers \u2014 healthier for the environment\n\u2714\ufe0f Gifts they\u2019ll use every single day\n\u2714\ufe0f Modern, calming colors for any home aesthetic\n\nGive intentional gifts made to be loved long past the holiday season."
              }
            </div>
          </div>
          <Guide1
            className={classNames("__wab_instance", sty.guide1__fWw1D)}
            slot={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___9Zx36
                )}
              >
                {"1"}
              </div>
            }
            slot2={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__pxSlb
                )}
              >
                {"Plush Pinehurst Bath Towel Sets"}
              </div>
            }
            slot3={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ok4E0
                )}
              >
                {
                  "Wrap them in everyday indulgence. \n\nThe Plush Pinehurst Collection is crafted with a dense, cloud-soft organic cotton weave that absorbs beautifully while keeping its luxurious feel. No shedding, no harsh chemicals \u2014 just pure comfort at its finest.\n\nPerfect for: Anyone who loves spa-level luxury, newlyweds, hosts, or those rebuilding their linen closet with truly premium quality."
                }
              </div>
            }
            slot4={
              <PlasmicLink__
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.link__w63DQ
                )}
                component={Link}
                href={"https://livegrund.com/collections/organic-bath-towels"}
                platform={"nextjs"}
                target={"_blank"}
              >
                {"Shop Towels \u2192"}
              </PlasmicLink__>
            }
          >
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.link__urTx
              )}
              component={Link}
              href={"https://livegrund.com/collections/organic-bath-towels"}
              platform={"nextjs"}
              target={"_blank"}
            >
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__sXlaa)}
                displayHeight={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "100%"
                    : "440px"
                }
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "100%"
                    : "440px"
                }
                loading={"eager"}
                src={{
                  src: "/plasmic/grund/images/guide1Png.png",
                  fullWidth: 800,
                  fullHeight: 800,
                  aspectRatio: undefined
                }}
              />
            </PlasmicLink__>
          </Guide1>
          <Guide1
            className={classNames("__wab_instance", sty.guide1___9FuMb)}
            slot={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__x3Dbq
                )}
              >
                {"2"}
              </div>
            }
            slot2={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__j6LfN
                )}
              >
                {"Fancy Prague Bath Towel Sets"}
              </div>
            }
            slot3={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___4XLa
                )}
              >
                {
                  "Elevated, refined, and effortlessly chic \u2014 the Fancy Prague Collection blends European sophistication with clean, toxin-free materials. \n\nThese towels are lightweight yet incredibly absorbent, drying quickly and maintaining a crisp, fresh feel with every wash.\n\nPerfect for: Minimalists, design lovers, clean-living enthusiasts, or anyone upgrading from scratchy, hotel-style towels."
                }
              </div>
            }
            slot4={
              <PlasmicLink__
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.link__ots55
                )}
                component={Link}
                href={"https://livegrund.com/collections/organic-bath-towels"}
                platform={"nextjs"}
                target={"_blank"}
              >
                {"Shop Towels \u2192"}
              </PlasmicLink__>
            }
          >
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.link__ftJbb
              )}
              component={Link}
              href={"https://livegrund.com/collections/organic-bath-towels"}
              platform={"nextjs"}
              target={"_blank"}
            >
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img___45Ok)}
                displayHeight={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "100%"
                    : "440px"
                }
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "100%"
                    : "440px"
                }
                loading={"eager"}
                src={{
                  src: "/plasmic/grund/images/guide2Png.png",
                  fullWidth: 800,
                  fullHeight: 800,
                  aspectRatio: undefined
                }}
              />
            </PlasmicLink__>
          </Guide1>
          <Guide1
            className={classNames("__wab_instance", sty.guide1___1Ooge)}
            slot={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__dfSts
                )}
              >
                {"3"}
              </div>
            }
            slot2={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__khRtE
                )}
              >
                {"Hand & Face Towel Sets \n(Pinehurst + Prague Collections)"}
              </div>
            }
            slot3={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___847Pk
                )}
              >
                {
                  "Small gifts with a luxurious impact. \n\nOur hand and face towel sets \u2014 available in both Pinehurst and Prague \u2014 deliver softness, absorbency, and toxin-free peace of mind. \n\nGentle on skin, beautiful in any bathroom.\n\nPerfect for: Stocking stuffers, guest bathroom upgrades, teacher gifts, or thoughtful add-ons."
                }
              </div>
            }
            slot4={
              <PlasmicLink__
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.link__wLbra
                )}
                component={Link}
                href={"https://livegrund.com/collections/organic-bath-towels"}
                platform={"nextjs"}
                target={"_blank"}
              >
                {"Shop Towels \u2192"}
              </PlasmicLink__>
            }
          >
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.link__uvc7
              )}
              component={Link}
              href={"https://livegrund.com/collections/organic-bath-towels"}
              platform={"nextjs"}
              target={"_blank"}
            >
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img___30T0J)}
                displayHeight={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "100%"
                    : "440px"
                }
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "100%"
                    : "440px"
                }
                loading={"eager"}
                src={{
                  src: "/plasmic/grund/images/guide3Png.png",
                  fullWidth: 800,
                  fullHeight: 800,
                  aspectRatio: undefined
                }}
              />
            </PlasmicLink__>
          </Guide1>
          <Guide1
            className={classNames("__wab_instance", sty.guide1__fykae)}
            slot={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ho75H
                )}
              >
                {"4"}
              </div>
            }
            slot2={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__bqE5D
                )}
              >
                {"Sea Pines All-Year Throw Blankets"}
              </div>
            }
            slot3={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__qhV55
                )}
              >
                {
                  "Lightweight, natural, and effortlessly stylish \u2014 the Sea Pines Throw brings year-round comfort to any space. \n\nWoven from breathable organic cotton, it\u2019s the perfect layering piece for cozy evenings, breezy mornings, and everything in between.\n\nPerfect for: Home d\u00e9cor lovers, coastal enthusiasts, hosts, or anyone who loves a touch of understated luxury."
                }
              </div>
            }
            slot4={
              <PlasmicLink__
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.link__amHNp
                )}
                component={Link}
                href={
                  "https://livegrund.com/collections/organic-throw-blankets/products/slate-gray-organic-throw-blankets"
                }
                platform={"nextjs"}
                target={"_blank"}
              >
                {"Shop Throws \u2192"}
              </PlasmicLink__>
            }
          >
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.link__wtB2
              )}
              component={Link}
              href={
                "https://livegrund.com/collections/organic-throw-blankets/products/slate-gray-organic-throw-blankets"
              }
              platform={"nextjs"}
              target={"_blank"}
            >
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__hh6VR)}
                displayHeight={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "100%"
                    : "440px"
                }
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "100%"
                    : "440px"
                }
                loading={"eager"}
                src={{
                  src: "/plasmic/grund/images/guide4Png.png",
                  fullWidth: 800,
                  fullHeight: 800,
                  aspectRatio: undefined
                }}
              />
            </PlasmicLink__>
          </Guide1>
          <Guide1
            className={classNames("__wab_instance", sty.guide1__lxV59)}
            slot={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__d3A7S
                )}
              >
                {"5"}
              </div>
            }
            slot2={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__oM2Wl
                )}
              >
                {"Spa-Like Luxury Bath Robes"}
              </div>
            }
            slot3={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__iO75
                )}
              >
                {
                  "Give the gift of slow mornings and soft evenings.\n\nOur luxury bath robes deliver warmth without heaviness and softness without synthetics \u2014 all in 100% organic cotton. \n\nNo static, no plastics, no toxins. Just pure, calming comfort.\n\nPerfect for: Homebodies, new parents, brides, self-care lovers, or anyone who deserves a daily dose of luxury."
                }
              </div>
            }
            slot4={
              <PlasmicLink__
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.link__uFti8
                )}
                component={Link}
                href={
                  "https://livegrund.com/products/organic-turkish-cotton-robe"
                }
                platform={"nextjs"}
                target={"_blank"}
              >
                {"Shop Robes \u2192"}
              </PlasmicLink__>
            }
          >
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.link___3PVpd
              )}
              component={Link}
              href={
                "https://livegrund.com/products/organic-turkish-cotton-robe"
              }
              platform={"nextjs"}
              target={"_blank"}
            >
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__uUupz)}
                displayHeight={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "100%"
                    : "440px"
                }
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "100%"
                    : "440px"
                }
                loading={"eager"}
                src={{
                  src: "/plasmic/grund/images/guide5Png.png",
                  fullWidth: 800,
                  fullHeight: 800,
                  aspectRatio: undefined
                }}
              />
            </PlasmicLink__>
          </Guide1>
          <Guide1
            className={classNames("__wab_instance", sty.guide1___7Wcl)}
            slot={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___2NYzf
                )}
              >
                {"6"}
              </div>
            }
            slot2={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__dlfuT
                )}
              >
                {"Luxury Bath Rugs (3 Styles for Every Home)"}
              </div>
            }
            slot3={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__x7XQb
                )}
              >
                {
                  "Choose from three beautifully crafted designs \u2014 each made from pure organic cotton for softness, durability, and a healthier home. \n\nUnlike synthetic rugs, ours never shed microplastics or trap harsh chemicals.\n\nPerfect for: Anyone who appreciates a clean, cohesive bathroom refresh, families, wellness lovers, or gift recipients who value high-quality home essentials."
                }
              </div>
            }
            slot4={
              <PlasmicLink__
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.link__ojZvq
                )}
                component={Link}
                href={
                  "https://livegrund.com/collections/organic-cotton-yarn-bath-rugs"
                }
                platform={"nextjs"}
                target={"_blank"}
              >
                {"Shop Rugs \u2192"}
              </PlasmicLink__>
            }
          >
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.link__pwOyJ
              )}
              component={Link}
              href={
                "https://livegrund.com/collections/organic-cotton-yarn-bath-rugs"
              }
              platform={"nextjs"}
              target={"_blank"}
            >
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__fnqwb)}
                displayHeight={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "100%"
                    : "440px"
                }
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "100%"
                    : "440px"
                }
                loading={"eager"}
                src={{
                  src: "/plasmic/grund/images/guide6Png.png",
                  fullWidth: 800,
                  fullHeight: 800,
                  aspectRatio: undefined
                }}
              />
            </PlasmicLink__>
          </Guide1>
          <div className={classNames(projectcss.all, sty.freeBox__uTpNx)}>
            <div
              data-plasmic-name={"heroHeadline5"}
              data-plasmic-override={overrides.heroHeadline5}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.heroHeadline5
              )}
            >
              {"40% Off Online Sale"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__brF5B
              )}
            >
              {
                "For a limited-time, we have extended our best deals from Black Friday and Cyber Monday for holiday gift shoppers. Get 40% off sitewide (no minimum order) or 50% off ($500 minimum order) plus free shipping on qualifying orders.\n\nGive the gift of luxury\u2026 without the toxins."
              }
            </div>
            <PlasmicLink__
              data-plasmic-name={"submitPhonebtn2"}
              data-plasmic-override={overrides.submitPhonebtn2}
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.submitPhonebtn2,
                "shake"
              )}
              component={Link}
              href={"https://livegrund.com/"}
              platform={"nextjs"}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__bkYu
                )}
              >
                {"Shop Now"}
              </div>
              <ArrowBigRightSvgIcon
                className={classNames(projectcss.all, sty.svg__cCpJe)}
                role={"img"}
              />
            </PlasmicLink__>
          </div>
          <div
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames(projectcss.all, sty.footer)}
          >
            <Embed
              data-plasmic-name={"embedHtml"}
              data-plasmic-override={overrides.embedHtml}
              className={classNames("__wab_instance", sty.embedHtml)}
              code={
                '<svg viewBox="0 0 1440 150" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="none" style="display: block; width: 100%; height: 100px;">\n  <path fill="#F5F5F5" d="M0,40 C480,120 960,0 1440,80 L1440,0 L0,0 Z"></path>\n</svg>'
              }
            />

            <div className={classNames(projectcss.all, sty.freeBox___27Etp)}>
              <div className={classNames(projectcss.all, sty.freeBox__rtzpb)}>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.link__s4Saa
                  )}
                  component={Link}
                  href={"https://livegrund.com/collections"}
                  platform={"nextjs"}
                  target={"_blank"}
                >
                  <PlasmicImg__
                    data-plasmic-name={"logo3"}
                    data-plasmic-override={overrides.logo3}
                    alt={""}
                    className={classNames(sty.logo3)}
                    displayHeight={"90px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"90px"}
                    loading={"eager"}
                    src={{
                      src: "/plasmic/grund/images/grundLogoWhiteVectorAvif.avif",
                      fullWidth: 340,
                      fullHeight: 117,
                      aspectRatio: undefined
                    }}
                  />
                </PlasmicLink__>
                <div
                  className={classNames(projectcss.all, sty.freeBox___4AQjr)}
                >
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__dPsvq
                    )}
                    component={Link}
                    href={"https://www.facebook.com/gelisleep"}
                    platform={"nextjs"}
                    target={"_blank"}
                  >
                    <Icons8FacebookSvgIcon
                      className={classNames(projectcss.all, sty.svg___09Jal)}
                      role={"img"}
                    />
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__jhdWl
                    )}
                    component={Link}
                    href={"https://www.x.com/gelisleep"}
                    platform={"nextjs"}
                    target={"_blank"}
                  >
                    <XLogoSvgIcon
                      className={classNames(projectcss.all, sty.svg___78D7)}
                      role={"img"}
                    />
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__khyN
                    )}
                    component={Link}
                    href={"https://www.instagram.com/gelisleep"}
                    platform={"nextjs"}
                    target={"_blank"}
                  >
                    <InstagramSvgIcon
                      className={classNames(projectcss.all, sty.svg__tFjq)}
                      role={"img"}
                    />
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link___4Bzyr
                    )}
                    component={Link}
                    href={"https://www.pinterest.com/Geli_Sleep"}
                    platform={"nextjs"}
                    target={"_blank"}
                  >
                    <Pinterest113SvgIcon
                      className={classNames(projectcss.all, sty.svg__qC9G)}
                      role={"img"}
                    />
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__uWBjO
                    )}
                    component={Link}
                    href={"https://www.tiktok.com/@gelisleep"}
                    platform={"nextjs"}
                    target={"_blank"}
                  >
                    <TiktokSvgrepoComSvgIcon
                      className={classNames(projectcss.all, sty.svg__euhLo)}
                      role={"img"}
                    />
                  </PlasmicLink__>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox___5OHy8)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__jxD3Z
                  )}
                >
                  {"SUPPORT"}
                </div>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__mD4Xo
                  )}
                  component={Link}
                  href={"https://livegrund.com/pages/about"}
                  platform={"nextjs"}
                  target={"_blank"}
                >
                  {"About Grund"}
                </PlasmicLink__>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link___3RfS4
                  )}
                  component={Link}
                  href={"https://livegrund.com/pages/contact-grund"}
                  platform={"nextjs"}
                  target={"_blank"}
                >
                  {"Contact Us"}
                </PlasmicLink__>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__kH1A
                  )}
                  component={Link}
                  href={"https://livegrund.com/blogs/organic-bed-and-bath"}
                  platform={"nextjs"}
                  target={"_blank"}
                >
                  {"Blog"}
                </PlasmicLink__>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__cn5Nf
                  )}
                  component={Link}
                  href={"https://livegrund.com/pages/faqs"}
                  platform={"nextjs"}
                  target={"_blank"}
                >
                  {"FAQs"}
                </PlasmicLink__>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__kzVdH
                  )}
                  component={Link}
                  href={"https://livegrund.com/pages/wholesale"}
                  platform={"nextjs"}
                  target={"_blank"}
                >
                  {"Wholesale"}
                </PlasmicLink__>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link___7UgbE
                  )}
                  component={Link}
                  href={
                    "https://livegrund.com/products/rise-ai-giftcard?_pos=1&_sid=9dff2dd2e&_ss=r"
                  }
                  platform={"nextjs"}
                  target={"_blank"}
                >
                  {"Gift Cards"}
                </PlasmicLink__>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__uPCaH)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__vOCnc
                  )}
                >
                  {"POLICIES"}
                </div>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__ld4WN
                  )}
                  component={Link}
                  href={"https://livegrund.com/pages/policies"}
                  platform={"nextjs"}
                  target={"_blank"}
                >
                  {"Our Policies"}
                </PlasmicLink__>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__tok8Z
                  )}
                  component={Link}
                  href={"https://livegrund.com/pages/returns"}
                  platform={"nextjs"}
                  target={"_blank"}
                >
                  {"Returns"}
                </PlasmicLink__>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__wZ8U4
                  )}
                  component={Link}
                  href={"https://www.gelisleep.com/pages/ccpa-opt-out"}
                  platform={"nextjs"}
                  target={"_blank"}
                >
                  {"Privacy Policy"}
                </PlasmicLink__>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__vL5Hl
                  )}
                  component={Link}
                  href={"https://www.gelisleep.com/pages/terms-and-conditions"}
                  platform={"nextjs"}
                  target={"_blank"}
                >
                  {"Terms & Conditions"}
                </PlasmicLink__>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__pTwjv
                  )}
                  component={Link}
                  href={"https://www.gelisleep.com/pages/patent-details"}
                  platform={"nextjs"}
                  target={"_blank"}
                >
                  {"Patent Details"}
                </PlasmicLink__>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox___284Oa)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__pXaj3
                  )}
                >
                  {"CONTACT"}
                </div>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__ml8S
                  )}
                  component={Link}
                  href={"https://www.gelisleep.com/pages/90-night-sleep-trial"}
                  platform={"nextjs"}
                  target={"_blank"}
                >
                  {"Help Center"}
                </PlasmicLink__>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__kctUm
                  )}
                  component={Link}
                  href={"https://www.gelisleep.com/pages/warranty"}
                  platform={"nextjs"}
                  target={"_blank"}
                >
                  {"Wholesale"}
                </PlasmicLink__>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__b9Oi
                  )}
                  component={Link}
                  href={"https://www.gelisleep.com/pages/ccpa-opt-out"}
                  platform={"nextjs"}
                  target={"_blank"}
                >
                  {"Affiliates"}
                </PlasmicLink__>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__bN7P)}>
              <div className={classNames(projectcss.all, sty.freeBox__vT6I)} />
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__cmGv7)}>
              <p
                data-plasmic-name={"p"}
                data-plasmic-override={overrides.p}
                className={classNames(
                  projectcss.all,
                  projectcss.p,
                  projectcss.__wab_text,
                  sty.p
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "\u00a9 2025 livegrund.com. All rights reserved."
                  : "\u00a9 2025 livegrund.com. All rights reserved."}
              </p>
              <div className={classNames(projectcss.all, sty.freeBox__lSuns)}>
                <A1Cc5C97117844C0Baed1B594B8441E1SvgIcon
                  className={classNames(projectcss.all, sty.svg__gkCg7)}
                  role={"img"}
                />

                <Fe59Bd81Eef94C38B993E0Cdfdef8E8BSvgIcon
                  className={classNames(projectcss.all, sty.svg__y8TAv)}
                  role={"img"}
                />

                <_58E3B3D164Ca451A8D6E3147Cef3AfaaSvgIcon
                  className={classNames(projectcss.all, sty.svg__usEbd)}
                  role={"img"}
                />

                <Fd6697B3506648Ff8DacF29E194083CdSvgIcon
                  className={classNames(projectcss.all, sty.svg__b6ClP)}
                  role={"img"}
                />

                <Fba2822A173B475C99DbFbc9F6Fd24A9SvgIcon
                  className={classNames(projectcss.all, sty.svg__omaxu)}
                  role={"img"}
                />

                <_7468Cfc1F2Dc4Fc4Bf3CEeb7F2B9066DSvgIcon
                  className={classNames(projectcss.all, sty.svg__cxiO7)}
                  role={"img"}
                />

                <_5Af63073Ff5042D9A4E20Eb614673309SvgIcon
                  className={classNames(projectcss.all, sty.svg__ovoeI)}
                  role={"img"}
                />

                <_44C55Ab9E76348D3Bbe8Ee81843921EfSvgIcon
                  className={classNames(projectcss.all, sty.svg__sm3X)}
                  role={"img"}
                />

                <F8Cb0Eb974Ed4071B0823B63F191Ba20SvgIcon
                  className={classNames(projectcss.all, sty.svg__aoJo)}
                  role={"img"}
                />
              </div>
            </div>
          </div>
          <Embed
            data-plasmic-name={"styles"}
            data-plasmic-override={overrides.styles}
            className={classNames("__wab_instance", sty.styles)}
            code={
              "\n<style>\n\n\n.shake {\n  animation: shakeLoop 6s infinite ease-in-out;\n}\n\n@keyframes shakeLoop {\n  0%   { transform: translateX(0); }\n  2%   { transform: translateX(-5px); }\n  4%   { transform: translateX(5px); }\n  6%   { transform: translateX(-5px); }\n  8%   { transform: translateX(5px); }\n  10%  { transform: translateX(-5px); }\n  12%  { transform: translateX(5px); }\n  14%  { transform: translateX(0); }\n  100% { transform: translateX(0); }\n}\n\n\n</style>\n\n\n\n\n\n\n<style>\n/* Load-in compatibility class */\n.load-in-compat {\n    transform: translateY(20px);\n    animation: loadInAnimationCompat 0.8s ease-out forwards;\n}\n\n/* Keyframes for the load-in animation */\n@keyframes loadInAnimationCompat {\n    0% {\n        opacity: 0;\n        transform: translateY(20px);\n    }\n    100% {\n        opacity: 1;\n        transform: translateY(0);\n    }\n}\n</style>\n"
            }
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "guide1Draft",
    "heroHeadline3",
    "paragraph25",
    "nav",
    "intro",
    "heroHeadline4",
    "heroHeadline5",
    "submitPhonebtn2",
    "footer",
    "embedHtml",
    "logo3",
    "p",
    "styles"
  ],
  guide1Draft: ["guide1Draft", "heroHeadline3", "paragraph25"],
  heroHeadline3: ["heroHeadline3"],
  paragraph25: ["paragraph25"],
  nav: ["nav"],
  intro: ["intro", "heroHeadline4"],
  heroHeadline4: ["heroHeadline4"],
  heroHeadline5: ["heroHeadline5"],
  submitPhonebtn2: ["submitPhonebtn2"],
  footer: ["footer", "embedHtml", "logo3", "p"],
  embedHtml: ["embedHtml"],
  logo3: ["logo3"],
  p: ["p"],
  styles: ["styles"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  guide1Draft: "div";
  heroHeadline3: "div";
  paragraph25: "div";
  nav: "div";
  intro: "div";
  heroHeadline4: "div";
  heroHeadline5: "div";
  submitPhonebtn2: "a";
  footer: "div";
  embedHtml: typeof Embed;
  logo3: typeof PlasmicImg__;
  p: "p";
  styles: typeof Embed;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicGuide__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicGuide__VariantsArgs;
    args?: PlasmicGuide__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicGuide__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicGuide__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicGuide__ArgProps,
          internalVariantPropNames: PlasmicGuide__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicGuide__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicGuide";
  } else {
    func.displayName = `PlasmicGuide.${nodeName}`;
  }
  return func;
}

export const PlasmicGuide = Object.assign(
  // Top-level PlasmicGuide renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    guide1Draft: makeNodeComponent("guide1Draft"),
    heroHeadline3: makeNodeComponent("heroHeadline3"),
    paragraph25: makeNodeComponent("paragraph25"),
    nav: makeNodeComponent("nav"),
    intro: makeNodeComponent("intro"),
    heroHeadline4: makeNodeComponent("heroHeadline4"),
    heroHeadline5: makeNodeComponent("heroHeadline5"),
    submitPhonebtn2: makeNodeComponent("submitPhonebtn2"),
    footer: makeNodeComponent("footer"),
    embedHtml: makeNodeComponent("embedHtml"),
    logo3: makeNodeComponent("logo3"),
    p: makeNodeComponent("p"),
    styles: makeNodeComponent("styles"),

    // Metadata about props expected for PlasmicGuide
    internalVariantProps: PlasmicGuide__VariantProps,
    internalArgProps: PlasmicGuide__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Why Live Grund?",
      description: "Because comfort should never come with compromise.",
      ogImageSrc:
        "https://site-assets.plasmic.app/89fbdf7d04787ec25d8d820c4fab02d0.png",
      canonical: ""
    }
  }
);

export default PlasmicGuide;
/* prettier-ignore-end */
