/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: sMD1pVj9GCeDqp5pGdZGXp
// Component: 9cjanN_n6Qis

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: sMD1pVj9GCeDqp5pGdZGXp/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: sMD1pVj9GCeDqp5pGdZGXp/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: sMD1pVj9GCeDqp5pGdZGXp/projectcss
import sty from "./PlasmicValueStack.module.css"; // plasmic-import: 9cjanN_n6Qis/css

createPlasmicElementProxy;

export type PlasmicValueStack__VariantMembers = {};
export type PlasmicValueStack__VariantsArgs = {};
type VariantPropType = keyof PlasmicValueStack__VariantsArgs;
export const PlasmicValueStack__VariantProps = new Array<VariantPropType>();

export type PlasmicValueStack__ArgsType = {
  children?: React.ReactNode;
  slot?: React.ReactNode;
  slot2?: React.ReactNode;
  slot3?: React.ReactNode;
  children2?: React.ReactNode;
  slot4?: React.ReactNode;
  slot5?: React.ReactNode;
  slot6?: React.ReactNode;
};
type ArgPropType = keyof PlasmicValueStack__ArgsType;
export const PlasmicValueStack__ArgProps = new Array<ArgPropType>(
  "children",
  "slot",
  "slot2",
  "slot3",
  "children2",
  "slot4",
  "slot5",
  "slot6"
);

export type PlasmicValueStack__OverridesType = {
  root?: Flex__<"div">;
  mobile?: Flex__<"div">;
  desktop?: Flex__<"div">;
};

export interface DefaultValueStackProps {
  children?: React.ReactNode;
  slot?: React.ReactNode;
  slot2?: React.ReactNode;
  slot3?: React.ReactNode;
  children2?: React.ReactNode;
  slot4?: React.ReactNode;
  slot5?: React.ReactNode;
  slot6?: React.ReactNode;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicValueStack__RenderFunc(props: {
  variants: PlasmicValueStack__VariantsArgs;
  args: PlasmicValueStack__ArgsType;
  overrides: PlasmicValueStack__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"mobile"}
        data-plasmic-override={overrides.mobile}
        className={classNames(projectcss.all, sty.mobile)}
      >
        <div className={classNames(projectcss.all, sty.freeBox__oPdj1)}>
          <div className={classNames(projectcss.all, sty.freeBox__eNpta)}>
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__nTjQs)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
            />
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__wrZoS)}>
            <div className={classNames(projectcss.all, sty.freeBox__yCcZq)}>
              {renderPlasmicSlot({
                defaultContents: (
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___0GH5C
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#636363" }}
                      >
                        {"30-Day Zendrop PLUS App Free Trial:"}
                      </span>
                    </React.Fragment>
                  </div>
                ),
                value: args.children,
                className: classNames(sty.slotTargetChildren)
              })}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__vwGp
              )}
            >
              {"Enter some text"}
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__nJzFa)}>
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.link__ed6Zq
              )}
              component={Link}
              href={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "https://zendrop.com/checkout-plus-fb/"
                  : "https://zendrop.com/checkout-trial-fb/"
              }
              platform={"nextjs"}
            >
              {renderPlasmicSlot({
                defaultContents: (
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link___6Rcag
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {"\ud83d\udc49  FREE  \ud83d\udc48"}
                  </PlasmicLink__>
                ),
                value: args.slot2
              })}
            </PlasmicLink__>
            <div className={classNames(projectcss.all, sty.freeBox__niyjY)}>
              <div className={classNames(projectcss.all, sty.freeBox__v3TBh)}>
                <div className={classNames(projectcss.all, sty.freeBox__oCUlX)}>
                  {renderPlasmicSlot({
                    defaultContents: "Price: $2,997",
                    value: args.slot,
                    className: classNames(sty.slotTargetSlot)
                  })}
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__y8Twp)}>
          <div className={classNames(projectcss.all, sty.freeBox__uYu62)}>
            <div className={classNames(projectcss.all, sty.freeBox___8DjMl)}>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__fqOMh)}
                displayHeight={"24px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"24px"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/grund/images/downloadSvg2.svg",
                  fullWidth: 150,
                  fullHeight: 150,
                  aspectRatio: 1
                }}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ueKu
                )}
              >
                {"Instant Access"}
              </div>
            </div>
          </div>
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__phNpb)}>
          <div className={classNames(projectcss.all, sty.freeBox__wy9CA)}>
            <div className={classNames(projectcss.all, sty.freeBox__sJAca)}>
              {renderPlasmicSlot({
                defaultContents:
                  "Network and learn from some of the top dropshippers on the planet. ",
                value: args.slot3
              })}
            </div>
          </div>
        </div>
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__r8TSa)}>
        <div
          data-plasmic-name={"desktop"}
          data-plasmic-override={overrides.desktop}
          className={classNames(projectcss.all, sty.desktop)}
        >
          <div className={classNames(projectcss.all, sty.freeBox__gnu30)}>
            <div className={classNames(projectcss.all, sty.freeBox__wEyVy)}>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__ilr0T)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
              />
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__j0JIw)}>
              <div className={classNames(projectcss.all, sty.freeBox___5Y8V)}>
                {renderPlasmicSlot({
                  defaultContents: (
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__abTx
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ color: "#636363" }}
                        >
                          {"30-Day Zendrop PLUS App Free Trial:"}
                        </span>
                      </React.Fragment>
                    </div>
                  ),
                  value: args.children2,
                  className: classNames(sty.slotTargetChildren2)
                })}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___7FbiT
                )}
              >
                {"Enter some text"}
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__v02Ny)}>
              <div className={classNames(projectcss.all, sty.freeBox__i02NL)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img___7Fto)}
                  displayHeight={"24px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"24px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/grund/images/downloadSvg2.svg",
                    fullWidth: 150,
                    fullHeight: 150,
                    aspectRatio: 1
                  }}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__yuVch
                  )}
                >
                  {"Instant Access"}
                </div>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__ps9E8)}>
              <div className={classNames(projectcss.all, sty.freeBox__yckcV)}>
                <div className={classNames(projectcss.all, sty.freeBox__dw6Iu)}>
                  {renderPlasmicSlot({
                    defaultContents: "Price: $2,997",
                    value: args.slot4,
                    className: classNames(sty.slotTargetSlot4)
                  })}
                </div>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__gl1Gd)}>
              <PlasmicLink__
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.link__ile4M
                )}
                component={Link}
                href={"https://zendrop.com/checkout-plus-fb/"}
                platform={"nextjs"}
              >
                {renderPlasmicSlot({
                  defaultContents: (
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__appss
                      )}
                    >
                      {"\ud83d\udc49  FREE  \ud83d\udc48"}
                    </div>
                  ),
                  value: args.slot5
                })}
              </PlasmicLink__>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__yuc1E)}>
            <div className={classNames(projectcss.all, sty.freeBox___00Mqa)}>
              <div className={classNames(projectcss.all, sty.freeBox__wj3Db)}>
                {renderPlasmicSlot({
                  defaultContents:
                    "Network and learn from some of the top dropshippers on the planet. ",
                  value: args.slot6
                })}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "mobile", "desktop"],
  mobile: ["mobile"],
  desktop: ["desktop"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  mobile: "div";
  desktop: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicValueStack__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicValueStack__VariantsArgs;
    args?: PlasmicValueStack__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicValueStack__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicValueStack__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicValueStack__ArgProps,
          internalVariantPropNames: PlasmicValueStack__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicValueStack__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicValueStack";
  } else {
    func.displayName = `PlasmicValueStack.${nodeName}`;
  }
  return func;
}

export const PlasmicValueStack = Object.assign(
  // Top-level PlasmicValueStack renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    mobile: makeNodeComponent("mobile"),
    desktop: makeNodeComponent("desktop"),

    // Metadata about props expected for PlasmicValueStack
    internalVariantProps: PlasmicValueStack__VariantProps,
    internalArgProps: PlasmicValueStack__ArgProps
  }
);

export default PlasmicValueStack;
/* prettier-ignore-end */
