/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: sMD1pVj9GCeDqp5pGdZGXp

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsgSzvTaFbvEJb } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: gSzvTAFbvEJb/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsgSzvTaFbvEJb
});
